version: "2.3"

services:
  db:
    build: ./bd
    volumes:
      - /bd/bd-files:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cdp
  backend:
    build: ./back-src
    volumes:
      - ./back-src:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    init: true
    links:
      - db
  frontend:
    build: ./front-src
    volumes:
      - ./front-src:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "4200:4200"
    init: true
    links:
      - backend
