version: "2.3"

#Compose pour dev

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cdp
    volumes:
      - ./bd/bdfiles:/var/lib/mysql
  backend:
    build: ./back-src
    volumes:
      - ./back-src:/home/node
      - home/node/node_modules
    command: npm run docker-dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    init: true
    links:
      - db
  frontend:
    build: ./front-src
    volumes:
      - ./front-src:/home/node
      - home/node/node_modules
    command: npm start
    ports:
      - "4200:4200"
    init: true
    links:
      - backend
