version: "2.3"

services:
  web:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    init: true
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /db:/data/db


